log:
  level: INFO

server:
  bind_address: 127.0.0.1
  bind_port: 15872

acme:
  # ACME directory server to use
  directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
  # ACME account to use (private key will get created if it does not exist)
  account_email: gbolo@linuxctl.com
  # DNS server to use for validating dns challenge
  dns_server: 8.8.8.8:53
  # currently ONLY digitalocean is supported...
  dns_provider: digitalocean
  ## you should set this via env var instead
  #digitalocean_token: dop_xxx

vault:
  address: "http://127.0.0.1:8200"
  # path where a KV (v2) secrets engine kv (v2) is mounted on
  kv2_mount: kv
  # path (relative to mount) where we want to store our secrets
  kv2_secret_path: platform/acme
  # skip TLS certificate verification (useful for self-signed certs in dev/test)
  tls_skip_verify: false
  ## you should set this via env var instead
  #token: xxx

# List of domains to manage (add your domains here)
domains:
  # - example.com
  # - "*.example.com"
